### 필수과제1
- 저번시간에 배운 스케일링 3가지를 가지고 전처리를 다르게 하여서
- KNN 모델링을 돌려보고 스케일링에 따른 결과 값이 어떤 식으로 바뀌는지 확인해 보자!
- 최적의 N은 몇 인지 체크해 보기!

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [12]:
df= pd.read_csv('wine_test.csv')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Unnamed: 0                    178 non-null    int64  
 1   alcohol                       176 non-null    float64
 2   malic_acid                    178 non-null    float64
 3   ash                           178 non-null    float64
 4   alcalinity_of_ash             178 non-null    float64
 5   magnesium                     178 non-null    int64  
 6   total_phenols                 178 non-null    float64
 7   flavanoids                    178 non-null    float64
 8   nonflavanoid_phenols          173 non-null    float64
 9   proanthocyanins               178 non-null    float64
 10  color_intensity               178 non-null    float64
 11  hue                           178 non-null    float64
 12  od280/od315_of_diluted_wines  178 non-null    float64
 13  proli

In [14]:
df['alcohol']=df['alcohol'].fillna(df['alcohol'].median())
df['nonflavanoid_phenols']=df['nonflavanoid_phenols'].fillna(df['nonflavanoid_phenols'].mean())

In [15]:
df.columns

Index(['Unnamed: 0', 'alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash',
       'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'class'],
      dtype='object')

In [16]:
df_n=df[['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash',
       'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'class']]

In [17]:
# 훈련데이터와 테스트데이터 나누기
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_n.drop('class',axis=1), df_n['class'],
                                                   test_size=0.3, random_state=111)

In [18]:
# 스케일링 기법
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
st_scaler= StandardScaler()
mm_scaler=MinMaxScaler()
rb_scaler=RobustScaler()

In [19]:
## knn 모델
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [20]:
# 정밀도
from sklearn.metrics import accuracy_score

**Standard Scaler:

In [22]:
# Standard Scaler 초기화
st_scaler = StandardScaler()

# 훈련 데이터에 스케일링 적용
x_train_st = st_scaler.fit_transform(x_train)
x_test_st = st_scaler.transform(x_test)

# 스케일링 된 데이터 출력
print("Scaled Training Data with Standard Scaler:\n", x_train_st)
print("\nScaled Testing Data with Standard Scaler:\n", x_test_st)

Scaled Training Data with Standard Scaler:
 [[-0.43530157 -1.18448679 -0.43569326 ...  1.23539226  0.84482654
  -0.97048643]
 [ 1.14734909 -0.54154105 -0.88747834 ... -0.20876178  1.09537442
   0.70060319]
 [ 1.52049437 -0.6242055   0.46787688 ...  1.23539226  0.34373078
   2.87145794]
 ...
 [-1.09152258 -0.60583562 -0.17215197 ...  1.6866904  -0.48160342
  -0.82992749]
 [-1.0143201  -0.89975368 -1.56515594 ... -0.43441085  0.63849299
  -1.40153385]
 [-1.50326909 -1.26715125  0.84436444 ... -0.75031955  0.72692165
  -0.75183919]]

Scaled Testing Data with Standard Scaler:
 [[-1.24592752e+00  1.86491301e+00  9.13893189e-02  8.74461126e-01
  -1.40415762e+00 -2.81147549e-01 -2.24478197e-01  4.18937186e-01
  -3.82481012e-01 -1.04882395e+00 -7.50319552e-01 -2.47219922e-02
  -5.64427273e-01]
 [ 5.36474162e-02  1.46077569e+00 -1.34503217e-01  1.02949856e+00
  -1.05896424e+00 -1.04679095e+00 -3.90287856e-01  1.92341545e+00
   9.76638805e-02 -1.00593111e-01 -5.24670482e-01 -8.50056193e-01
  -7.

**MinMax Scaler:

In [23]:
# MinMax Scaler 초기화
mm_scaler = MinMaxScaler()

# 훈련 데이터에 스케일링 적용
x_train_mm = mm_scaler.fit_transform(x_train)
x_test_mm = mm_scaler.transform(x_test)

# 스케일링 된 데이터 출력
print("Scaled Training Data with MinMax Scaler:\n", x_train_mm)
print("\nScaled Testing Data with MinMax Scaler:\n", x_test_mm)

Scaled Training Data with MinMax Scaler:
 [[0.33757962 0.01832994 0.56410256 ... 0.75824176 0.6900369  0.11510791]
 [0.72929936 0.16089613 0.48717949 ... 0.40659341 0.75276753 0.5       ]
 [0.82165605 0.14256619 0.71794872 ... 0.75824176 0.56457565 1.        ]
 ...
 [0.17515924 0.14663951 0.60897436 ... 0.86813187 0.35793358 0.14748201]
 [0.19426752 0.0814664  0.37179487 ... 0.35164835 0.63837638 0.01582734]
 [0.07324841 0.         0.78205128 ... 0.27472527 0.66051661 0.16546763]]

Scaled Testing Data with MinMax Scaler:
 [[ 0.13694268  0.69450102  0.65384615  0.69512195  0.10869565  0.36363636
   0.3699422   0.54716981  0.32752613  0.11262799  0.27472527  0.47232472
   0.20863309]
 [ 0.45859873  0.60488798  0.61538462  0.72560976  0.16304348  0.2
   0.32369942  0.90566038  0.42160279  0.3003413   0.32967033  0.26568266
   0.1618705 ]
 [ 0.5955414   0.18737271  0.67307692  0.60365854  0.32608696  0.58181818
   0.72543353  0.24528302  0.50522648  0.32593857  0.54945055  0.80442804
   0.

**Robust Scaler:

In [24]:
# Robust Scaler 초기화
rb_scaler = RobustScaler()

# 훈련 데이터에 스케일링 적용
x_train_rb = rb_scaler.fit_transform(x_train)
x_test_rb = rb_scaler.transform(x_test)

# 스케일링 된 데이터 출력
print("Scaled Training Data with Robust Scaler:\n", x_train_rb)
print("\nScaled Testing Data with Robust Scaler:\n", x_test_rb)

Scaled Training Data with Robust Scaler:
 [[-0.28897338 -0.60111317 -0.34042553 ...  0.79411765  0.33057851
  -0.47338501]
 [ 0.64638783 -0.08163265 -0.68085106 ... -0.14705882  0.47107438
   0.63255814]
 [ 0.86692015 -0.14842301  0.34042553 ...  0.79411765  0.04958678
   2.06925065]
 ...
 [-0.67680608 -0.13358071 -0.14184397 ...  1.08823529 -0.41322314
  -0.38036176]
 [-0.63117871 -0.37105751 -1.19148936 ... -0.29411765  0.21487603
  -0.75865633]
 [-0.92015209 -0.66790353  0.62411348 ... -0.5         0.26446281
  -0.32868217]]

Scaled Testing Data with Robust Scaler:
 [[-0.76806084  1.86270872  0.05673759  0.72727273 -0.98630137 -0.2115869
  -0.14756672  0.45454545 -0.22981366 -0.64829822 -0.5        -0.15702479
  -0.20465116]
 [ 0.          1.53617811 -0.11347518  0.84848485 -0.71232877 -0.66498741
  -0.24803768  1.60606061  0.10559006  0.06482982 -0.35294118 -0.61983471
  -0.33901809]
 [ 0.3269962   0.0148423   0.14184397  0.36363636  0.10958904  0.3929471
   0.62480377 -0.51515152 